-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    hooks:
    -   id: debug-statements
        exclude: {{ cookiecutter.pkg_name }}/config/app_template/
    -   id: flake8
    -   id: check-json
    -   id: check-case-conflict

-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 'ebb1b1bb080b0c960bcf37cf81d09185cec4fc6d'
    hooks:
    -   id: pep257
        exclude: tests/
